package androidx.compose.material3.tokens;

import androidx.compose.ui.text.font.FontWeight;
import androidx.compose.ui.text.font.GenericFontFamily;
import androidx.compose.ui.unit.TextUnit;
import kotlin.ResultKt;

/* loaded from: classes.dex */
public abstract class TypeScaleTokens {
    public static final GenericFontFamily BodyLargeFont;
    public static final long BodyLargeLineHeight;
    public static final long BodyLargeSize;
    public static final long BodyLargeTracking;
    public static final FontWeight BodyLargeWeight;
    public static final GenericFontFamily BodyMediumFont;
    public static final long BodyMediumLineHeight;
    public static final long BodyMediumSize;
    public static final long BodyMediumTracking;
    public static final FontWeight BodyMediumWeight;
    public static final GenericFontFamily BodySmallFont;
    public static final long BodySmallLineHeight;
    public static final long BodySmallSize;
    public static final long BodySmallTracking;
    public static final FontWeight BodySmallWeight;
    public static final GenericFontFamily DisplayLargeFont;
    public static final long DisplayLargeLineHeight;
    public static final long DisplayLargeSize;
    public static final long DisplayLargeTracking;
    public static final FontWeight DisplayLargeWeight;
    public static final GenericFontFamily DisplayMediumFont;
    public static final long DisplayMediumLineHeight;
    public static final long DisplayMediumSize;
    public static final long DisplayMediumTracking;
    public static final FontWeight DisplayMediumWeight;
    public static final GenericFontFamily DisplaySmallFont;
    public static final long DisplaySmallLineHeight;
    public static final long DisplaySmallSize;
    public static final long DisplaySmallTracking;
    public static final FontWeight DisplaySmallWeight;
    public static final GenericFontFamily HeadlineLargeFont;
    public static final long HeadlineLargeLineHeight;
    public static final long HeadlineLargeSize;
    public static final long HeadlineLargeTracking;
    public static final FontWeight HeadlineLargeWeight;
    public static final GenericFontFamily HeadlineMediumFont;
    public static final long HeadlineMediumLineHeight;
    public static final long HeadlineMediumSize;
    public static final long HeadlineMediumTracking;
    public static final FontWeight HeadlineMediumWeight;
    public static final GenericFontFamily HeadlineSmallFont;
    public static final long HeadlineSmallLineHeight;
    public static final long HeadlineSmallSize;
    public static final long HeadlineSmallTracking;
    public static final FontWeight HeadlineSmallWeight;
    public static final GenericFontFamily LabelLargeFont;
    public static final long LabelLargeLineHeight;
    public static final long LabelLargeSize;
    public static final long LabelLargeTracking;
    public static final FontWeight LabelLargeWeight;
    public static final GenericFontFamily LabelMediumFont;
    public static final long LabelMediumLineHeight;
    public static final long LabelMediumSize;
    public static final long LabelMediumTracking;
    public static final FontWeight LabelMediumWeight;
    public static final GenericFontFamily LabelSmallFont;
    public static final long LabelSmallLineHeight;
    public static final long LabelSmallSize;
    public static final long LabelSmallTracking;
    public static final FontWeight LabelSmallWeight;
    public static final GenericFontFamily TitleLargeFont;
    public static final long TitleLargeLineHeight;
    public static final long TitleLargeSize;
    public static final long TitleLargeTracking;
    public static final FontWeight TitleLargeWeight;
    public static final GenericFontFamily TitleMediumFont;
    public static final long TitleMediumLineHeight;
    public static final long TitleMediumSize;
    public static final long TitleMediumTracking;
    public static final FontWeight TitleMediumWeight;
    public static final GenericFontFamily TitleSmallFont;
    public static final long TitleSmallLineHeight;
    public static final long TitleSmallSize;
    public static final long TitleSmallTracking;
    public static final FontWeight TitleSmallWeight;

    static {
        GenericFontFamily genericFontFamily = TypefaceTokens.Plain;
        BodyLargeFont = genericFontFamily;
        BodyLargeLineHeight = ResultKt.getSp(24.0d);
        BodyLargeSize = ResultKt.getSp(16);
        BodyLargeTracking = ResultKt.getSp(0.5d);
        FontWeight fontWeight = TypefaceTokens.WeightRegular;
        BodyLargeWeight = fontWeight;
        BodyMediumFont = genericFontFamily;
        BodyMediumLineHeight = ResultKt.getSp(20.0d);
        BodyMediumSize = ResultKt.getSp(14);
        BodyMediumTracking = ResultKt.getSp(0.2d);
        BodyMediumWeight = fontWeight;
        BodySmallFont = genericFontFamily;
        BodySmallLineHeight = ResultKt.getSp(16.0d);
        BodySmallSize = ResultKt.getSp(12);
        BodySmallTracking = ResultKt.getSp(0.4d);
        BodySmallWeight = fontWeight;
        GenericFontFamily genericFontFamily2 = TypefaceTokens.Brand;
        DisplayLargeFont = genericFontFamily2;
        DisplayLargeLineHeight = ResultKt.getSp(64.0d);
        DisplayLargeSize = ResultKt.getSp(57);
        long sp = ResultKt.getSp(0.2d);
        if (!(!ResultKt.m297isUnspecifiedR2X_6o(sp))) {
            throw new IllegalArgumentException("Cannot perform operation for Unspecified type.".toString());
        }
        DisplayLargeTracking = ResultKt.pack(-TextUnit.m285getValueimpl(sp), sp & 1095216660480L);
        DisplayLargeWeight = fontWeight;
        DisplayMediumFont = genericFontFamily2;
        DisplayMediumLineHeight = ResultKt.getSp(52.0d);
        DisplayMediumSize = ResultKt.getSp(45);
        DisplayMediumTracking = ResultKt.getSp(0.0d);
        DisplayMediumWeight = fontWeight;
        DisplaySmallFont = genericFontFamily2;
        DisplaySmallLineHeight = ResultKt.getSp(44.0d);
        DisplaySmallSize = ResultKt.getSp(36);
        DisplaySmallTracking = ResultKt.getSp(0.0d);
        DisplaySmallWeight = fontWeight;
        HeadlineLargeFont = genericFontFamily2;
        HeadlineLargeLineHeight = ResultKt.getSp(40.0d);
        HeadlineLargeSize = ResultKt.getSp(32);
        HeadlineLargeTracking = ResultKt.getSp(0.0d);
        HeadlineLargeWeight = fontWeight;
        HeadlineMediumFont = genericFontFamily2;
        HeadlineMediumLineHeight = ResultKt.getSp(36.0d);
        HeadlineMediumSize = ResultKt.getSp(28);
        HeadlineMediumTracking = ResultKt.getSp(0.0d);
        HeadlineMediumWeight = fontWeight;
        HeadlineSmallFont = genericFontFamily2;
        HeadlineSmallLineHeight = ResultKt.getSp(32.0d);
        HeadlineSmallSize = ResultKt.getSp(24);
        HeadlineSmallTracking = ResultKt.getSp(0.0d);
        HeadlineSmallWeight = fontWeight;
        LabelLargeFont = genericFontFamily;
        LabelLargeLineHeight = ResultKt.getSp(20.0d);
        LabelLargeSize = ResultKt.getSp(14);
        LabelLargeTracking = ResultKt.getSp(0.1d);
        FontWeight fontWeight2 = TypefaceTokens.WeightMedium;
        LabelLargeWeight = fontWeight2;
        LabelMediumFont = genericFontFamily;
        LabelMediumLineHeight = ResultKt.getSp(16.0d);
        LabelMediumSize = ResultKt.getSp(12);
        LabelMediumTracking = ResultKt.getSp(0.5d);
        LabelMediumWeight = fontWeight2;
        LabelSmallFont = genericFontFamily;
        LabelSmallLineHeight = ResultKt.getSp(16.0d);
        LabelSmallSize = ResultKt.getSp(11);
        LabelSmallTracking = ResultKt.getSp(0.5d);
        LabelSmallWeight = fontWeight2;
        TitleLargeFont = genericFontFamily2;
        TitleLargeLineHeight = ResultKt.getSp(28.0d);
        TitleLargeSize = ResultKt.getSp(22);
        TitleLargeTracking = ResultKt.getSp(0.0d);
        TitleLargeWeight = fontWeight;
        TitleMediumFont = genericFontFamily;
        TitleMediumLineHeight = ResultKt.getSp(24.0d);
        TitleMediumSize = ResultKt.getSp(16);
        TitleMediumTracking = ResultKt.getSp(0.2d);
        TitleMediumWeight = fontWeight2;
        TitleSmallFont = genericFontFamily;
        TitleSmallLineHeight = ResultKt.getSp(20.0d);
        TitleSmallSize = ResultKt.getSp(14);
        TitleSmallTracking = ResultKt.getSp(0.1d);
        TitleSmallWeight = fontWeight2;
    }
}
